# Change these first
owner: oribisoftware # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Marketing Website (oribi.se)
    url: https://oribi.se
    icon: https://oribi.se/wp-content/uploads/2020/01/oribi-favicon.png
    assignees:
      - nilslockean
  - name: Oribi Web Store (oribisoftware.com)
    url: https://oribisoftware.com/en
    icon: https://easydigitaldownloads.com/wp-content/uploads/2018/12/favicon-128x128.png
    assignees:
      - nilslockean
  - name: Oribi Web Store / License key server (E-keys)
    url: $EDD_LICENSE_ENDPOINT/?edd_action=check_license&item_name=test&license=1234
    icon: https://easydigitaldownloads.com/wp-content/uploads/2018/12/favicon-128x128.png
    assignees:
      - nilslockean
  - name: Habitat (dl.oribisoftware.com)
    url: https://dl.oribisoftware.com
    icon: https://oribi.se/wp-content/uploads/2020/01/oribi-favicon.png
    assignees:
      - nilslockean
  - name: Habitat / License key server (H-keys)
    url: $HABITAT_LICENSE_ENDPOINT/1234
    icon: https://oribi.se/wp-content/uploads/2020/01/oribi-favicon.png
    assignees:
      - nilslockean
  - name: Habitat / Domain name license check
    url: $HABITAT_DOMAINCHECK_ENDPOINT/oribi.se
    icon: https://oribi.se/wp-content/uploads/2020/01/oribi-favicon.png
    assignees:
      - nilslockean
  - name: Habitat / School ID license check
    url: $HABITAT_SCHOOLID_ENDPOINT/2147483646
    icon: https://oribi.se/wp-content/uploads/2020/01/oribi-favicon.png
    assignees:
      - nilslockean
  # - name: Databas för användarinställningar i Office-tillägg
  #   url: $USER_SETTINGS_MYSQL_ENDPOINT/oribispeak
  #   assignees:
  #     - glosboken
  - name: TTS (Oribi Speak)
    url: $TTS_ENDPOINT/speak
    icon: https://dev--oribi-speak-light.netlify.app/favicon.ico
    method: POST
    headers:
      - 'Content-Type: application/json'
    body: '{ "text": "detta är ett test", "voice": "elin" }'
    assignees:
      - nilslockean
  - name: Word Prediction (Oribi Speak)
    url: $PREDICTION_ENDPOINT
    icon: https://oribi-speak-light.netlify.app/favicon.ico
    method: POST
    headers:
      - 'Accept: application/json'
      - 'Content-Type: application/json'
    body: '{ "input": "test", "apiKey": "$PREDICTION_API_KEY" }'
    assignees:
      - nilslockean
  - name: Dictionary API
    url: $DICTIONARY_ENDPOINT/?language=swe&word=test
    icon: https://orilex.netlify.app/favicon.ico
    __dangerous__body_down: '[]'
    assignees:
      - glosboken
  - name: Dictionary API / Available phonfiles
    url: $DICTIONARY_SOUNDS_ENDPOINT
    icon: https://orilex.netlify.app/favicon.ico
    assignees:
      - nilslockean
  - name: Spellcheck Service (SkrivaText)
    url: $SPELLCHECK_ENDPOINT
    icon: https://oribi.se/wp-content/uploads/2021/03/icon_128x128@2x.png
    method: POST
    headers:
      - 'Content-Type: application/json'
    body: '{ "text": "abåre" }'
    assignees:
      - nilslockean

status-website:
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /upptime
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: status.oribi.se
  theme: night
  logoUrl: https://raw.githubusercontent.com/oribisoftware/upptime/master/assets/icon-dark.svg
  favicon: https://oribi.se/wp-content/uploads/2020/01/oribi-favicon.png
  name: Server Status
  introTitle: '**Server down?** Find up to date information about Oribi\'s services.'
  introMessage: This site will ping the listed services every 5 minutes and alert a developer if issues arise. A more thorough test suite is run every 12 hours by [Postman](https://go.postman.co/workspace/Oribi-Team-Workspace~a7f3260d-f4d1-4306-8861-17fbb8c067eb/collection/1128059-3522d8f6-d6db-4aaa-87f8-d61e7867d7ad).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Postman
      href: https://oribisoftware.postman.co
